#pragma once

// Embedded WebUI (generated by scripts/embed_webui.py at build time).
// The real llama.cpp WebUI (tools/ui) lives INSIDE barskuy-llm.exe:
// no separate frontend dir, no Next.js. Single binary, ala llama-server.

#include <cstddef>
#include <cstdint>
#include <string>

namespace barskuy::api::webui {

struct Entry {
    const char* path;
    const char* mime;
    const uint8_t* data;
    size_t size;
};

const Entry* find(const std::string& path);
size_t count();

} // namespace barskuy::api::webui
