#!/usr/bin/env python3
"""Embed built WebUI dist (llama.cpp tools/ui) as a C++ byte table.

Usage: embed_webui.py <dist_dir> <out_cpp>
Regenerate when the UI dist changes, then rebuild barskuy-llm.
"""
import os
import sys

MIME = {
    ".html": "text/html",
    ".js": "text/javascript",
    ".css": "text/css",
    ".json": "application/json",
    ".svg": "image/svg+xml",
    ".png": "image/png",
    ".ico": "image/x-icon",
    ".webmanifest": "application/manifest+json",
    ".txt": "text/plain",
    ".map": "application/json",
}

SKIP_DIRS = set()  # keep recommended-mcp icons (MCP dialog references them)


FAVICON_SVG = """<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64"><rect width="64" height="64" rx="12" fill="#1f2937"/><path d="M36 8 L18 36 h12 L26 56 L46 26 h-13 z" fill="#fbbf24"/></svg>
"""


def main():
    dist, out = sys.argv[1], sys.argv[2]
    # F9-10: ensure a favicon exists (pwa-assets step is skipped in our build)
    fav = os.path.join(dist, "favicon.svg")
    if not os.path.exists(fav):
        with open(fav, "w", encoding="utf-8") as f:
            f.write(FAVICON_SVG)
    files = []
    for root, dirs, names in os.walk(dist):
        dirs[:] = [d for d in dirs if d not in SKIP_DIRS]
        for n in sorted(names):
            p = os.path.join(root, n)
            rel = os.path.relpath(p, dist).replace(os.sep, "/")
            if rel.startswith("sw.js") or rel.startswith("workbox-"):
                continue  # skip PWA service worker when embedded
            with open(p, "rb") as f:
                files.append((rel, f.read()))

    with open(out, "w", encoding="utf-8") as o:
        o.write("// AUTO-GENERATED by scripts/embed_webui.py - do not edit\n")
        o.write('#include "webui_embed.hpp"\n\n')
        o.write("namespace barskuy::api::webui {\n\n")
        for i, (rel, data) in enumerate(files):
            ext = os.path.splitext(rel)[1].lower()
            mime = MIME.get(ext, "application/octet-stream")
            o.write(f"static const uint8_t kBytes{i}[] = {{")
            o.write(",".join(str(b) for b in data))
            o.write("};\n")
            o.write(f"// {rel} ({len(data)} bytes, {mime})\n")
        o.write("\nstatic const Entry kEntries[] = {\n")
        for i, (rel, data) in enumerate(files):
            ext = os.path.splitext(rel)[1].lower()
            mime = MIME.get(ext, "application/octet-stream")
            o.write(f'    {{"{rel}", "{mime}", kBytes{i}, sizeof(kBytes{i})}},\n')
        o.write("};\n\n")
        o.write("const Entry* find(const std::string& path) {\n")
        o.write("    std::string p = path;\n")
        o.write('    if (p.empty() || p == "/") p = "index.html";\n')
        o.write('    if (!p.empty() && p[0] == \'/\') p.erase(0, 1);\n')
        o.write("    for (auto& e : kEntries) if (p == e.path) return &e;\n")
        o.write("    return nullptr;\n}\n\n")
        o.write("size_t count() { return sizeof(kEntries) / sizeof(kEntries[0]); }\n\n")
        o.write("} // namespace barskuy::api::webui\n")
    total = sum(len(d) for _, d in files)
    print(f"embedded {len(files)} files, {total} bytes -> {out}")


if __name__ == "__main__":
    main()
